# Generated by Django 2.2.16 on 2020-09-19 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cat', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_person', models.CharField(max_length=30)),
                ('is_manager', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Categories')),
                ('name_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Persons')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024)),
                ('ask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Questions')),
                ('name_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Persons')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('ask', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.Questions')),
                ('text', models.CharField(max_length=1024)),
                ('name_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Persons')),
            ],
        ),
    ]
