# Generated by Django 2.2.16 on 2020-09-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200919_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persons',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
